from __future__ import annotations

import re
import textwrap
from dataclasses import dataclass
from pathlib import Path


@dataclass(slots=True)
class ScaffoldResult:
    project_name: str
    module_name: str
    root_dir: Path
    created_files: list[Path]


def slugify_project_name(project_name: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", project_name).strip("-")
    return slug.lower() or "ml-project"


def module_name_for(project_name: str) -> str:
    return slugify_project_name(project_name).replace("-", "_")


def create_project_scaffold(
    project_name: str,
    destination_dir: str | Path | None = None,
    overwrite: bool = False,
) -> ScaffoldResult:
    module_name = module_name_for(project_name)
    project_dir = Path(destination_dir or Path.cwd()) / slugify_project_name(project_name)
    if project_dir.exists() and not overwrite:
        raise FileExistsError(f"Project directory already exists: {project_dir}")
    project_dir.mkdir(parents=True, exist_ok=True)

    files = _project_files(project_name=project_name, module_name=module_name)
    created: list[Path] = []
    for relative_path, content in files.items():
        absolute_path = project_dir / relative_path
        absolute_path.parent.mkdir(parents=True, exist_ok=True)
        absolute_path.write_text(content, encoding="utf-8")
        created.append(absolute_path)

    return ScaffoldResult(
        project_name=project_name,
        module_name=module_name,
        root_dir=project_dir,
        created_files=created,
    )


def _project_files(project_name: str, module_name: str) -> dict[str, str]:
    return {
        "pyproject.toml": textwrap.dedent(
            f"""
            [build-system]
            requires = ["setuptools>=68", "wheel"]
            build-backend = "setuptools.build_meta"

            [project]
            name = "{slugify_project_name(project_name)}"
            version = "0.1.0"
            description = "ML project scaffold generated by ml init"
            requires-python = ">=3.10"
            dependencies = ["ml-platform-toolkit>=0.1.0", "torch>=2.2"]

            [tool.setuptools]
            package-dir = {{"" = "src"}}

            [tool.setuptools.packages.find]
            where = ["src"]
            """
        ).strip()
        + "\n",
        "README.md": textwrap.dedent(
            f"""
            # {project_name}

            Generated ML project scaffold.

            ## Commands

            - `python -m {module_name}.train --config configs/training.json`
            - `python -m {module_name}.evaluate --config configs/evaluation.json`
            """
        ).strip()
        + "\n",
        f"src/{module_name}/__init__.py": "__all__ = []\n",
        f"src/{module_name}/config.py": textwrap.dedent(
            """
            from __future__ import annotations

            from dataclasses import dataclass
            from pathlib import Path
            import json


            @dataclass(slots=True)
            class ProjectConfig:
                project_name: str
                seed: int = 42
                epochs: int = 5
                batch_size: int = 32
                learning_rate: float = 0.001

                @classmethod
                def load(cls, path: str | Path) -> "ProjectConfig":
                    payload = json.loads(Path(path).read_text(encoding="utf-8"))
                    return cls(**payload)

                def save(self, path: str | Path) -> Path:
                    destination = Path(path)
                    destination.parent.mkdir(parents=True, exist_ok=True)
                    destination.write_text(
                        json.dumps(
                            {
                                "project_name": self.project_name,
                                "seed": self.seed,
                                "epochs": self.epochs,
                                "batch_size": self.batch_size,
                                "learning_rate": self.learning_rate,
                            },
                            indent=2,
                            sort_keys=True,
                        ),
                        encoding="utf-8",
                    )
                    return destination
            """
        ).strip()
        + "\n",
        f"src/{module_name}/model.py": textwrap.dedent(
            """
            from __future__ import annotations

            try:
                import torch
                from torch import nn
            except Exception as exc:  # pragma: no cover - template fallback
                raise RuntimeError(
                    "This project template expects PyTorch to be installed."
                ) from exc


            class BinaryClassifier(nn.Module):
                def __init__(self, input_dim: int = 2, hidden_dim: int = 16) -> None:
                    super().__init__()
                    self.network = nn.Sequential(
                        nn.Linear(input_dim, hidden_dim),
                        nn.ReLU(),
                        nn.Linear(hidden_dim, 1),
                    )

                def forward(self, inputs: torch.Tensor) -> torch.Tensor:
                    return self.network(inputs).squeeze(-1)
            """
        ).strip()
        + "\n",
        f"src/{module_name}/trainer.py": textwrap.dedent(
            """
            from __future__ import annotations

            try:
                import torch
                from torch import nn
            except Exception as exc:  # pragma: no cover - template fallback
                raise RuntimeError(
                    "This project template expects PyTorch to be installed."
                ) from exc

            from ml_platform.core.config import ExperimentConfig
            from ml_platform.training.base import BaseTrainer

            from .model import BinaryClassifier


            class PyTorchBinaryTrainer(BaseTrainer):
                def __init__(self, config: ExperimentConfig, tracker=None) -> None:
                    super().__init__(config=config, tracker=tracker)
                    hidden_dim = int(config.model.get("hidden_dim", 16))
                    learning_rate = float(config.training.get("learning_rate", 0.001))
                    self.model = BinaryClassifier(hidden_dim=hidden_dim)
                    self.loss_fn = nn.BCEWithLogitsLoss()
                    self.optimizer = torch.optim.Adam(self.model.parameters(), lr=learning_rate)

                def train_step(self, batch, epoch_index: int):
                    del epoch_index
                    features, targets = batch
                    inputs = torch.as_tensor(features, dtype=torch.float32)
                    labels = torch.as_tensor(targets, dtype=torch.float32)
                    logits = self.model(inputs)
                    loss = self.loss_fn(logits, labels)
                    self.optimizer.zero_grad()
                    loss.backward()
                    self.optimizer.step()
                    predictions = (torch.sigmoid(logits) >= 0.5).to(torch.float32)
                    accuracy = (predictions == labels).to(torch.float32).mean().item()
                    return {{"loss": float(loss.item()), "accuracy": float(accuracy)}}

                def evaluate_step(self, batch, epoch_index: int):
                    del epoch_index
                    features, targets = batch
                    inputs = torch.as_tensor(features, dtype=torch.float32)
                    labels = torch.as_tensor(targets, dtype=torch.float32)
                    with torch.no_grad():
                        logits = self.model(inputs)
                        loss = self.loss_fn(logits, labels)
                        predictions = (torch.sigmoid(logits) >= 0.5).to(torch.float32)
                        accuracy = (predictions == labels).to(torch.float32).mean().item()
                    return {{"val_loss": float(loss.item()), "val_accuracy": float(accuracy)}}
            """
        ).strip()
        + "\n",
        f"src/{module_name}/train.py": textwrap.dedent(
            """
            from __future__ import annotations

            import argparse
            import json
            from pathlib import Path
            from random import Random

            from .config import ProjectConfig
            from .trainer import PyTorchBinaryTrainer


            def build_batches(seed: int, size: int = 64) -> list[tuple[list[float], list[int]]]:
                rng = Random(seed)
                features = [[rng.random(), rng.random()] for _ in range(size)]
                targets = [1 if sample[0] + sample[1] > 1 else 0 for sample in features]
                return [(features, targets)]


            def train(config: ProjectConfig) -> dict[str, float]:
                batches = build_batches(config.seed)
                trainer = PyTorchBinaryTrainer(config=config)
                result = trainer.fit(batches, batches)
                return result.metrics


            def main() -> None:
                parser = argparse.ArgumentParser()
                parser.add_argument("--config", default="configs/training.json")
                parser.add_argument("--output", default="artifacts/train_metrics.json")
                args = parser.parse_args()

                config = ProjectConfig.load(args.config)
                metrics = train(config)
                output_path = Path(args.output)
                output_path.parent.mkdir(parents=True, exist_ok=True)
                output_path.write_text(
                    json.dumps(metrics, indent=2, sort_keys=True),
                    encoding="utf-8",
                )
                print(output_path)


            if __name__ == "__main__":
                main()
            """
        ).strip()
        + "\n",
        f"src/{module_name}/evaluate.py": textwrap.dedent(
            """
            from __future__ import annotations

            import argparse
            import json
            from pathlib import Path

            from .config import ProjectConfig


            def evaluate(config: ProjectConfig) -> dict[str, object]:
                labels = [0, 1]
                y_true = [0, 1, 1, 0]
                y_pred = [0, 1, 0, 0]
                confusion_matrix = [[2, 0], [1, 1]]
                return {
                    "project_name": config.project_name,
                    "labels": labels,
                    "accuracy": 0.75,
                    "confusion_matrix": confusion_matrix,
                    "latency_ms": {"average": 4.2, "p95": 5.1},
                }


            def main() -> None:
                parser = argparse.ArgumentParser()
                parser.add_argument("--config", default="configs/evaluation.json")
                parser.add_argument("--output", default="artifacts/evaluation_report.json")
                args = parser.parse_args()

                config = ProjectConfig.load(args.config)
                report = evaluate(config)
                output_path = Path(args.output)
                output_path.parent.mkdir(parents=True, exist_ok=True)
                output_path.write_text(
                    json.dumps(report, indent=2, sort_keys=True),
                    encoding="utf-8",
                )
                print(output_path)


            if __name__ == "__main__":
                main()
            """
        ).strip()
        + "\n",
        "configs/training.json": textwrap.dedent(
            f"""
            {{
              "project_name": "{project_name}",
              "seed": 42,
              "epochs": 5,
              "batch_size": 32,
              "learning_rate": 0.001
            }}
            """
        ).strip()
        + "\n",
        "configs/evaluation.json": textwrap.dedent(
            f"""
            {{
              "project_name": "{project_name}",
              "seed": 42,
              "epochs": 1,
              "batch_size": 32,
              "learning_rate": 0.001
            }}
            """
        ).strip()
        + "\n",
        "Dockerfile": textwrap.dedent(
            f"""
            FROM python:3.11-slim
            WORKDIR /app
            COPY . /app
            RUN pip install --no-cache-dir .
            CMD ["python", "-m", "{module_name}.train"]
            """
        ).strip()
        + "\n",
        ".github/workflows/ci.yml": textwrap.dedent(
            f"""
            name: ci

            on:
              push:
              pull_request:

            jobs:
              validate:
                runs-on: ubuntu-latest
                steps:
                  - uses: actions/checkout@v4
                  - uses: actions/setup-python@v5
                    with:
                      python-version: "3.11"
                  - run: pip install .
                  - run: python -m unittest discover -s tests
                  - run: >
                      python -m {module_name}.train --config configs/training.json
                      --output artifacts/train_metrics.json
                  - run: >
                      python -m {module_name}.evaluate --config configs/evaluation.json
                      --output artifacts/evaluation_report.json
            """
        ).strip()
        + "\n",
        "tests/test_smoke.py": textwrap.dedent(
            f"""
            import unittest
            from pathlib import Path

            from {module_name}.config import ProjectConfig
            from {module_name}.train import train


            class SmokeTest(unittest.TestCase):
                def test_training_template_runs(self) -> None:
                    config = ProjectConfig(project_name="{project_name}")
                    metrics = train(config)
                    self.assertIn("val_accuracy", metrics)
                    self.assertIn("val_loss", metrics)


            if __name__ == "__main__":
                unittest.main()
            """
        ).strip()
        + "\n",
    }
